# Generated by Django 2.2.17 on 2021-02-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0003_auto_20210131_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(related_name='_customuser_followers_+', to='SNS.CustomUser'),
        ),
    ]
