# Generated by Django 2.2.17 on 2021-02-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0004_customuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='customuser',
            name='likes',
            field=models.ManyToManyField(to='SNS.Post'),
        ),
    ]
